name: Scheduled health check

on:
    schedule:
        - cron: '*/5 * * * *'

jobs: 
    health_check:
        runs-on: ubuntu-20.04
        steps:
            - name: Check the deployed service URL
              uses: jtalk/url-health-check-action@v4
              with:
              # Check the following URLs one by one sequentially
                url: https://full-stack-open-pokedex-y3e2.onrender.com
              # Follow redirects, or just report success on 3xx status codes
              # Fail this action after this many failed attempts
                max-attempts: 3 # Optional, defaults to 1
              
           
            

